### ISSUE TITLE
Behavior when there are dots in property names

### ISSUE THREAD

**Issue by b-gran** [Zertz/moredots#1]
Just wondering what the ideal behavior is when input objects have property names with dots in them.

In the following example, the output is the same for both objects, making it impossible to correctly reconstruct the original object based only on the output.

Does this library want consumers to be able to unambiguously reconstruct the input object based only on the output? Or is this library meant to be "one-way" in the sense that it doesn't care if the original object can be recovered?

```
const p = {
    foo: {
        '.bar': 1
    }
}

const q = {
    'foo.': {
        bar: 1
    }
}

console.log(moredots(p))
console.log(moredots(q))
```

`output`
```
{ 'foo..bar': 1 }
{ 'foo..bar': 1 }
```

**Comment by Zertz** [comment]
The module itself is only designed to flatten objects, not rebuild them. While this is an interesting edge case, I'm not convinced it is problematic, although perhaps it should be documented.
